from typing import Optional, Tuple, Protocol, runtime_checkable

import numpy as np

from py3r.media.types import VideoFrame, HasImage


@runtime_checkable
class VideoSource(Protocol):
    """A pull-based, minimal interface. Keep it small & capability-based."""
    # --- lifecycle
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...

    # --- capabilities/probing (callable pre-open; stable after open)
    def has_timing(self) -> bool: ...
    def has_fps(self) -> bool: ...
    def has_size(self) -> bool: ...
    def has_num_frames(self) -> bool: ...  # Has a known number of frames
    def is_seekable(self) -> bool: ...

    def get_size(self) -> Optional[Tuple[int, int]]: ...     # (width, height) or None if variable
    def get_fps(self) -> Optional[float]: ...
    def get_num_channels(self) -> int: ...                   # 1 or 3 (or more for special devices)
    def get_num_frames(self) -> Optional[int]: ...               # or None if live/unknown

    # --- control (optional; no-ops for sources that don’t support them)
    def set_playback_rate(self, mode: str) -> None: ...
    # mode in {"original_speed", "max_speed"} (files/images). For live cams, ignored.
    def seek(self, frame_index: int) -> None: ...
    def enable_grayscale(self, gray: bool) -> None: ...

    # --- acquisition
    def read(self, timeout: Optional[float] = None) -> Optional[VideoFrame]:
        """
        Return next Frame, or None on end-of-stream (EOS).
        Should block until a frame is available (or timeout).
        """
        ...


@runtime_checkable
class VideoWriter(Protocol):
    """A minimal interface for writing video frames to a sink."""
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...

    def write(self, frame: HasImage | np.ndarray) -> None: ...
