from typing import Optional, Tuple, Protocol, runtime_checkable

from py3r.media.types import VideoFrame


@runtime_checkable
class VideoSource(Protocol):
    """A pull-based, minimal interface. Keep it small & capability-based."""
    # --- lifecycle
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...

    # --- capabilities/probing (callable pre-open; stable after open)
    def name(self) -> str: ...
    def has_timing(self) -> bool: ...
    def has_fixed_fps(self) -> bool: ...
    def has_fixed_size(self) -> bool: ...
    def is_seekable(self) -> bool: ...

    def get_fps(self) -> Optional[float]: ...
    def get_size(self) -> Optional[Tuple[int, int]]: ...     # (width, height) or None if variable
    def get_num_channels(self) -> int: ...                   # 1 or 3 (or more for special devices)

    # --- control (optional; no-ops for sources that don’t support them)
    def set_playback_rate(self, mode: str) -> None: ...
    # mode in {"original_speed", "max_speed"} (files/images). For live cams, ignored.
    def seek(self, frame_index: int) -> None: ...
    def enable_grayscale(self, gray: bool) -> None: ...

    # --- acquisition
    def read(self, timeout: Optional[float] = None) -> Optional[VideoFrame]:
        """
        Return next Frame, or None on end-of-stream (EOS).
        Should block until a frame is available (or timeout).
        """
        ...